-- Oh My Template - Seed Data
-- Supabase SQL Editor에서 실행 (slug, lang) 단위로 en/ko 행을 각각 생성

insert into templates (slug, lang, name, category, description, thumbnail_url, price, status, sort_order, is_featured) values
('airline', 'en', 'Airline', 'hospitality', 'Premium airline booking and travel experience template', '/templates/airline/og-image.jpg', 0, 'published', 1, false),
('airline', 'ko', '에어라인', 'hospitality', '프리미엄 항공 예약 및 여행 경험 템플릿', '/templates/airline/og-image.jpg', 0, 'published', 1, false),
('car', 'en', 'Car Showroom', 'retail', 'Luxury car showroom and model showcase template', '/templates/car/og-image.jpg', 0, 'published', 2, false),
('car', 'ko', '자동차 쇼룸', 'retail', '럭셔리 자동차 쇼룸 및 모델 소개 템플릿', '/templates/car/og-image.jpg', 0, 'published', 2, false),
('cosmetic', 'en', 'Cosmetic Store', 'lifestyle', 'Beauty and cosmetic brand store template', '/templates/cosmetic/og-image.jpg', 0, 'published', 3, false),
('cosmetic', 'ko', '코스메틱 스토어', 'lifestyle', '뷰티 코스메틱 브랜드 스토어 템플릿', '/templates/cosmetic/og-image.jpg', 0, 'published', 3, false),
('dashboard', 'en', 'Dashboard', 'service', 'Analytics and business intelligence dashboard template', '/templates/dashboard/og-image.jpg', 0, 'published', 4, true),
('dashboard', 'ko', '대시보드', 'service', '분석 및 비즈니스 인텔리전스 대시보드 템플릿', '/templates/dashboard/og-image.jpg', 0, 'published', 4, true),
('docs', 'en', 'Documentation', 'service', 'Documentation workspace and knowledge base template', '/templates/docs/og-image.jpg', 0, 'published', 5, false),
('docs', 'ko', '문서 시스템', 'service', '문서 협업 워크스페이스 및 지식 베이스 템플릿', '/templates/docs/og-image.jpg', 0, 'published', 5, false),
('exhibition', 'en', 'Exhibition', 'portfolio', 'Museum and art exhibition showcase template', '/templates/exhibition/og-image.jpg', 0, 'published', 6, true),
('exhibition', 'ko', '전시관', 'portfolio', '미술관 및 전시 쇼케이스 템플릿', '/templates/exhibition/og-image.jpg', 0, 'published', 6, true),
('fashion', 'en', 'Fashion Store', 'lifestyle', 'Elegant fashion brand store and lookbook template', '/templates/fashion/og-image.jpg', 0, 'published', 7, false),
('fashion', 'ko', '패션 스토어', 'lifestyle', '엘레강트한 패션 브랜드 스토어 및 룩북 템플릿', '/templates/fashion/og-image.jpg', 0, 'published', 7, false),
('furniture', 'en', 'Furniture Modern', 'retail', 'Clean and modern furniture store template', '/templates/furniture/og-image.jpg', 0, 'published', 8, false),
('furniture', 'ko', '퍼니처 모던', 'retail', '깔끔하고 현대적인 가구 스토어 템플릿', '/templates/furniture/og-image.jpg', 0, 'published', 8, false),
('ir', 'en', 'IR', 'corporate', 'Investor relations and financial reporting template', '/templates/ir/og-image.jpg', 0, 'published', 9, false),
('ir', 'ko', 'IR', 'corporate', '투자자 관계 및 재무 보고 템플릿', '/templates/ir/og-image.jpg', 0, 'published', 9, false),
('jewelry', 'en', 'Jewelry', 'lifestyle', 'Luxury jewelry brand store template', '/templates/jewelry/og-image.jpg', 0, 'published', 10, false),
('jewelry', 'ko', '주얼리', 'lifestyle', '럭셔리 주얼리 브랜드 스토어 템플릿', '/templates/jewelry/og-image.jpg', 0, 'published', 10, false),
('magazine', 'en', 'Magazine', 'media', 'Editorial magazine and content publishing template', '/templates/magazine/og-image.jpg', 0, 'published', 11, false),
('magazine', 'ko', '매거진', 'media', '에디토리얼 매거진 및 콘텐츠 퍼블리싱 템플릿', '/templates/magazine/og-image.jpg', 0, 'published', 11, false),
('multi-shop', 'en', 'Multi Shop', 'retail', 'Multi-category shopping mall template', '/templates/multi-shop/og-image.jpg', 0, 'published', 12, false),
('multi-shop', 'ko', '멀티샵', 'retail', '멀티 카테고리 쇼핑몰 템플릿', '/templates/multi-shop/og-image.jpg', 0, 'published', 12, false),
('newspaper', 'en', 'Newspaper', 'media', 'Online newspaper and news portal template', '/templates/newspaper/og-image.jpg', 0, 'published', 13, false),
('newspaper', 'ko', '신문', 'media', '온라인 신문 및 뉴스 포털 템플릿', '/templates/newspaper/og-image.jpg', 0, 'published', 13, false),
('portfolio', 'en', 'Portfolio', 'portfolio', 'Creative portfolio and personal branding template', '/templates/portfolio/og-image.jpg', 0, 'published', 14, false),
('portfolio', 'ko', '포트폴리오', 'portfolio', '크리에이티브 포트폴리오 및 퍼스널 브랜딩 템플릿', '/templates/portfolio/og-image.jpg', 0, 'published', 14, false),
('sneaker', 'en', 'Sneaker Store', 'retail', 'Sneaker and streetwear culture store template', '/templates/sneaker/og-image.jpg', 0, 'published', 15, false),
('sneaker', 'ko', '스니커 스토어', 'retail', '스니커 및 스트리트웨어 문화 스토어 템플릿', '/templates/sneaker/og-image.jpg', 0, 'published', 15, false),
('studio', 'en', 'Studio', 'portfolio', 'Creative studio and project showcase template', '/templates/studio/og-image.jpg', 0, 'published', 16, true),
('studio', 'ko', '스튜디오', 'portfolio', '크리에이티브 스튜디오 및 프로젝트 쇼케이스 템플릿', '/templates/studio/og-image.jpg', 0, 'published', 16, true),
('technology', 'en', 'Technology - Robotflow', 'corporate', 'AI robotics company and technology showcase template', '/templates/technology/og-image.jpg', 0, 'published', 17, false),
('technology', 'ko', '테크놀로지 - 로봇플로우', 'corporate', 'AI 로봇 기업 및 기술 쇼케이스 템플릿', '/templates/technology/og-image.jpg', 0, 'published', 17, false);
