import { Exhibition, GalleryEvent } from './types';

export const exhibitions: Exhibition[] = [
  {
    slug: 'echoes-of-form',
    name: 'Echoes of Form',
    artist: 'Sophie Laurent',
    status: 'on-show',
    dateFrom: '2026년 3월 1일',
    dateTo: '2026년 5월 31일',
    showroom: '메인 갤러리',
    tags: { genre: '회화', theme: '정체성', ageRating: '18세 이상' },
    image: '/templates/OHMT003-exhibition/exhibition-01.jpg',
    heroImage: '/templates/OHMT003-exhibition/exhibition-hero-01.jpg',
    description:
      '소피 로랑의 첫 개인전은 유기적인 형태와 건축 구조가 맞닿는 지점을 살펴봅니다. 대형 회화에는 자유로운 붓질과 정교한 기하학이 한 화면 안에 겹쳐집니다. 가까이 다가갈수록 밑그림과 반복된 선, 덧칠의 흔적이 드러납니다. 초기 목탄 드로잉부터 최근 혼합 매체 작업까지 작가의 형식적 변화를 함께 소개합니다.',
  },
  {
    slug: 'skin-and-steel',
    name: 'Skin & Steel',
    artist: 'Marcus Webb',
    status: 'on-show',
    dateFrom: '2026년 2월 15일',
    dateTo: '2026년 6월 30일',
    showroom: '동관',
    tags: { genre: '조각', theme: '산업', ageRating: '16세 이상' },
    image: '/templates/OHMT003-exhibition/exhibition-02.jpg',
    heroImage: '/templates/OHMT003-exhibition/exhibition-hero-02.jpg',
    description:
      '마커스 웹은 고철, 재생 목재, 산업용 철물을 조합해 무게와 균형에 대한 감각을 다시 묻습니다. 거대한 구조물은 단단해 보이지만 일부 지점에서 아슬아슬한 균형을 유지합니다. 작품의 거친 표면과 동관의 정제된 공간이 선명한 대비를 이룹니다.',
  },
  {
    slug: 'light-residue',
    name: 'Light Residue',
    artist: 'Yuki Tanaka',
    status: 'on-show',
    dateFrom: '2026년 4월 1일',
    dateTo: '2026년 7월 31일',
    showroom: '프로젝트 홀',
    tags: { genre: '설치', theme: '자연', ageRating: '12세 이상' },
    image: '/templates/OHMT003-exhibition/exhibition-03.jpg',
    heroImage: '/templates/OHMT003-exhibition/exhibition-hero-03.jpg',
    description:
      '다나카 유키는 시간에 따라 달라지는 자연광을 재료로 삼아 몰입형 설치를 구성합니다. 반투명 막과 투사 영상, 섬세한 공간 장치가 빛의 방향과 밝기에 반응하며 전시장의 풍경을 천천히 바꿉니다.',
  },
  {
    slug: 'uncertain-ground',
    name: 'Uncertain Ground',
    artist: 'Aria Novak',
    status: 'opening-soon',
    dateFrom: '2026년 7월 1일',
    dateTo: '2026년 9월 30일',
    showroom: '사진 갤러리',
    tags: { genre: '사진', theme: '사회', ageRating: '14세 이상' },
    image: '/templates/OHMT003-exhibition/exhibition-04.jpg',
    heroImage: '/templates/OHMT003-exhibition/exhibition-hero-04.jpg',
    description:
      '아리아 노박은 빠르게 재편되는 도시의 가장자리와 그곳에 사는 사람들을 기록합니다. 5년 동안 네 대륙 20개 도시를 오가며 이주와 개발 속에서 삶의 터전을 지켜가는 공동체의 일상을 사진에 담았습니다.',
  },
  {
    slug: 'new-primitives',
    name: 'New Primitives',
    artist: 'Collective Studio',
    status: 'opening-soon',
    dateFrom: '2026년 8월 15일',
    dateTo: '2026년 10월 31일',
    showroom: '가든 갤러리',
    tags: { genre: '혼합 매체', theme: '문화', ageRating: '12세 이상' },
    image: '/templates/OHMT003-exhibition/exhibition-05.jpg',
    heroImage: '/templates/OHMT003-exhibition/exhibition-hero-05.jpg',
    description:
      '여섯 나라에서 활동하는 신진 작가 12명이 오늘의 시각 언어가 어떻게 만들어지고 공유되는지 살펴봅니다. 조각, 섬유, 디지털 미디어, 퍼포먼스를 넘나들며 서로 다른 문화적 전통과 동시대적 감각이 만나는 장면을 보여줍니다.',
  },
  {
    slug: 'after-the-fact',
    name: 'After the Fact',
    artist: 'Daniel Reeves',
    status: 'permanent',
    dateFrom: '2025년 1월 1일',
    dateTo: '상설',
    showroom: '상설전시실',
    tags: { genre: '개념미술', theme: '정체성', ageRating: '18세 이상' },
    image: '/templates/OHMT003-exhibition/exhibition-06.jpg',
    heroImage: '/templates/OHMT003-exhibition/exhibition-hero-06.jpg',
    description:
      'OHMT가 2024년에 소장한 대니얼 리브스의 주요 작품을 중심으로, 기억과 기록, 역사 서사를 다뤄온 30년의 작업을 소개합니다. 시기별 대표작과 관련 자료를 함께 구성했으며, 전시장 내 아카이브에서 작가의 노트와 제작 기록을 열람할 수 있습니다.',
  },
];

export const events: GalleryEvent[] = [
  {
    id: 'evt-01',
    title: '작가와의 대화: 소피 로랑',
    date: '2026년 6월 14일',
    time: '15:00',
    type: '작가 토크',
    ageRating: '18세 이상',
    image: '/templates/OHMT003-exhibition/event-01.jpg',
  },
  {
    id: 'evt-02',
    title: '관찰 드로잉 워크숍',
    date: '2026년 6월 21일',
    time: '10:00',
    type: '워크숍',
    ageRating: '12세 이상',
    image: '/templates/OHMT003-exhibition/event-02.jpg',
  },
  {
    id: 'evt-03',
    title: '큐레이터 전시 해설: Echoes of Form',
    date: '2026년 6월 28일',
    time: '14:00',
    type: '전시 해설',
    ageRating: '전체 관람가',
    image: '/templates/OHMT003-exhibition/event-03.jpg',
  },
  {
    id: 'evt-04',
    title: '라이브 퍼포먼스: 공간 속의 몸',
    date: '2026년 7월 5일',
    time: '19:30',
    type: '퍼포먼스',
    ageRating: '16세 이상',
    image: '/templates/OHMT003-exhibition/event-04.jpg',
  },
];
